#!/usr/bin/env bash
# Bash script that displays information about subdomains

function audit_subdomain {
  local domain=$1
  local subdomain=$2

  if [[ -z $subdomain ]]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
  else
    subdomains=("$subdomain")
  fi

  for sub in "${subdomains[@]}"; do
    record_type=$(dig +short -t CNAME "$sub.$domain" | awk '{print "CNAME"}')
    if [[ -z $record_type ]]; then
      record_type=$(dig +short -t A "$sub.$domain" | awk '{print "A"}')
    fi

    destination=$(dig +short "$sub.$domain" | awk 'NR==1{print $1}')

    if [[ -n $destination ]]; then
      echo "The subdomain $sub is a $record_type record and points to $destination"
    else
      echo "The subdomain $sub does not exist"
    fi
  done
}

domain=$1
subdomain=$2

if [[ -z $domain ]]; then
  echo "Please provide a domain name."
  exit 1
fi

audit_subdomain "$domain" "$subdomain"
