#!/usr/bin/env bash
# Bash script to Transfer file from localhost to a remote server using scp command.
# Ensurre the the assed parameters are just 4
if ['$#' -ne 4]; then
	echo "USAGE: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
# Assign meaningful variable name to the input parameters
PATH_TO_FILE="$1"
IP_ADDRESS="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"
# Use the secure copy command to copy the file from localhost to the remote server
scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP_ADDRESS":~/
