#!/usr/bin/env bash
# Bash csript to install and configure nginx on the remote server

sudo apt-get update
sudo apt-get -y install nginx
sudo echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html

sudo service nginx restart 


