#!/usr/bin/env bash
# Bash csript to install and configure nginx on the remote server

sudo apt-get update -y
sudo apt-get -y install nginx
sudo echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "19i rewrite ^/redirect_me https://twitter.com/home;" /etc/nginx/sites-enabled/default
sudo service nginx restart 


