#!/usr/bin/env bash
# Configure nginx to have a custom 404 page that contains the string 'Ceci n'est pas une page'

sudo apt-get update -y
sudo apt-get -y install nginx
sudo echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "50i rewrite ^/redirect_me https://twitter.com/home;" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/page_error_404.html

sudo sed -i '37i error_page 404 /page_error_404.html;\nlocation = /page_error_404.html {\nroot /usr/share/nginx/html; \ninternal;\n}\n' /etc/nginx/sites-enabled/default
sodu nginx -t
sudo service nginx restart 
