#!/usr/bin/env bash
# Install and configure HAproxy on the lb-01 server.
# Admin Redundancy 181408-web-01 and 181408-web-02
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8

sudo apt-get -y update
sudo apt-get install -y haproxy

sudo chmod 764 /etc/haproxy/
sudo chmod 764 /etc/haproxy/haproxy.cfg

sudo sed -i "$ a frontend Local_Server \n\t bind *:80 \n\t mode http \n\t default_backend My_Web_Servers \n\nbackend My_Web_Servers \n\t mode http \n\t balance roundrobin \n\t server 181408-web-01 52.86.247.157:80 check \n\t server 181408-web-02 54.90.47.55:80 check \n" /etc/haproxy/haproxy.cfg

sudo service haproxy restart
