#!/usr/bin/env bash

# Find the PID of the "4-to_infinity_and_beyond" process using pgrep
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Check if a PID was found
if [ -n "$pid" ]; then
  # Send the SIGTERM signal to the process to stop it gracefully
  kill "$pid"
fi
