#!/usr/bin/env bash
# display "To infinity and beyond" indefinitely
#+ with "sleep 2" between each iteration.
#+ display "I am invinsible!!!" when receiving a SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM
while :
do
	echo "To infinity and beyond"
	sleep 2
done
